version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: currency_exchanger_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: currency_exchanger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI Application
  app:
    build: .
    container_name: currency_exchanger_app
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: currency_exchanger
      DATABASE_HOSTNAME: db  # This is the key change!
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres_data: